title: Mengxi Jiang's Homepage
page-top-title: Mengxi Jiang
top-section-bg-text: Computer Science
home-subtitle: Mengxi Jiang&ensp;|&ensp;姜梦茜
copyright-text: '&copy; Mengxi Jiang 2024-2025. All Rights Reserved.'
